# Generated by Django 6.0 on 2026-02-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('chat', 'Chat Response'), ('ca', 'Current Affairs Item')], max_length=10)),
                ('reference', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('subtopic', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaMainsDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('subtopic', models.CharField(blank=True, max_length=150)),
                ('mains_points', models.TextField(blank=True, help_text='Bullet-style mains points')),
                ('mains_question', models.TextField(blank=True, help_text='One mains-style question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CA Mains Digest',
                'verbose_name_plural': 'CA Mains Digests',
                'indexes': [models.Index(fields=['date'], name='news_summar_date_e82d46_idx'), models.Index(fields=['subject', 'subtopic'], name='news_summar_subject_51868c_idx')],
            },
        ),
    ]
